import Image from "next/image";

import { brandLogos } from "@/content/brand-logos";

/**
 * Twelve logos from twelve sources. Set at one CSS height, a square mark like
 * FootJoy reads three times the size of a long wordmark like Sun Mountain, so
 * each one is sized to the same optical area instead: height falls as the
 * square root of the artwork's aspect ratio, bounded so nothing runs away.
 *
 * The files under public/brands are generated by
 * scripts/normalize-brand-logos.mjs: trimmed, single ink, transparent.
 * Logos are third party trademarks, dropped in rather than drawn here.
 */
const AREA = 54;
const MAX_WIDTH = 180;
const MAX_HEIGHT = 50;

/**
 * Hand corrections. Area alone is not enough: a bold slab like PING reads
 * heavier than its box, and a lockup that stacks a mark over a small caption,
 * Cleveland or Vokey Design, spends most of its height on detail the eye
 * does not count.
 */
const opticalTweak: Record<string, number> = {
  callaway: 1.14,
  cleveland: 1.2,
  footjoy: 0.94,
  odyssey: 1.1,
  ping: 0.86,
  "scotty-cameron": 1.26,
  "sun-mountain": 1.08,
  titleist: 0.94,
  vokey: 1.18,
};

export function BrandLogo({
  slug,
  name,
  className = "",
  imageClassName = "",
}: {
  slug: string;
  name: string;
  className?: string;
  /** applied only to a real logo file, never to the text fallback */
  imageClassName?: string;
}) {
  const logo = brandLogos[slug];

  if (!logo) {
    return (
      <span
        className={`text-[1.0625rem] uppercase tracking-[0.12em] ${className}`}
      >
        {name}
      </span>
    );
  }

  const tweak = opticalTweak[slug] ?? 1;
  let height = Math.min((AREA / Math.sqrt(logo.ratio)) * tweak, MAX_HEIGHT);
  let width = height * logo.ratio;

  if (width > MAX_WIDTH) {
    width = MAX_WIDTH;
    height = width / logo.ratio;
  }

  return (
    <Image
      src={`/brands/${slug}.png`}
      alt={name}
      width={Math.round(width * 4)}
      height={Math.round(height * 4)}
      style={{
        width: `${width.toFixed(1)}px`,
        height: `${height.toFixed(1)}px`,
      }}
      className={`object-contain ${className} ${imageClassName}`}
    />
  );
}
