export type Category =
  | "clubs"
  | "balls"
  | "bags"
  | "gloves"
  | "headwear"
  | "accessories";

export type Product = {
  slug: string;
  brand: string;
  model: string;
  category: Category;
  subcategory?: string;
  /** pence, so the page never does floating point money */
  price: number;
  statement: string;
  image: string;
  alt: string;
  inStock: boolean;
  fittingRecommended?: boolean;
  /** the number a fitter would quote about this product */
  detail: string;
  /** on the homepage grid, four at a time */
  featured?: boolean;
};

/**
 * Photography is the manufacturers' own studio work, cut to one tile by
 * scripts/build-product-shots.mjs. Anything listed here needs a real packshot
 * behind it, so the rack is the products we can show properly.
 */
export const products: Product[] = [
  {
    slug: "taylormade-p790-irons",
    brand: "TaylorMade",
    model: "P790 Irons",
    category: "clubs",
    subcategory: "irons",
    price: 149900,
    statement: "Forged face, hollow body, distance without the look.",
    image: "/images/products/taylormade-p790-irons.jpg",
    alt: "A TaylorMade P790 seven iron at address, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "7 clubs, 4 to PW",
    featured: true,
  },
  {
    slug: "titleist-pro-v1",
    brand: "Titleist",
    model: "Pro V1",
    category: "balls",
    price: 5200,
    statement: "The ball most of the field plays, for reasons.",
    image: "/images/products/titleist-pro-v1.jpg",
    alt: "A box of a dozen Titleist Pro V1 golf balls",
    inStock: true,
    detail: "Dozen",
    featured: true,
  },
  {
    slug: "ping-hoofer-lite",
    brand: "Ping",
    model: "Hoofer Lite",
    category: "bags",
    price: 23900,
    statement: "Two kilos on the shoulder, four hours on the feet.",
    image: "/images/products/ping-hoofer-lite.jpg",
    alt: "A Ping Hoofer Lite stand bag, legs out, on white",
    inStock: true,
    detail: "2.0 kg carry weight",
    featured: true,
  },
  {
    slug: "cleveland-rtx-6-zipcore",
    brand: "Cleveland",
    model: "RTX 6 ZipCore",
    category: "clubs",
    subcategory: "wedges",
    price: 15900,
    statement: "Four grinds off one head. Most players are on the wrong one.",
    image: "/images/products/cleveland-rtx6-zipcore.jpg",
    alt: "A Cleveland RTX 6 ZipCore wedge in tour satin, on white",
    inStock: false,
    fittingRecommended: true,
    detail: "46 to 60 degrees",
    featured: true,
  },
  {
    slug: "callaway-elyte-max-fast",
    brand: "Callaway",
    model: "Elyte Max Fast",
    category: "clubs",
    subcategory: "drivers",
    price: 47900,
    statement: "Light through the whole club, for players who have stopped swinging hard.",
    image: "/images/products/callaway-elyte-max-fast.jpg",
    alt: "A Callaway Elyte Max Fast driver head, sole and toe, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "10.5 and 12 degrees",
  },
  {
    slug: "ping-g440-max-fairway",
    brand: "Ping",
    model: "G440 Max Fairway",
    category: "clubs",
    subcategory: "fairway woods",
    price: 29900,
    statement: "The club most bags are missing, and the one most players skip.",
    image: "/images/products/ping-g440-max-fairway.jpg",
    alt: "A Ping G440 Max three wood, seen from the toe, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "3, 4, 5 and 7 wood",
  },
  {
    slug: "srixon-zxi-hybrid",
    brand: "Srixon",
    model: "ZXi Hybrid",
    category: "clubs",
    subcategory: "hybrids",
    price: 21900,
    statement: "Replaces the long iron you have not hit well since you bought it.",
    image: "/images/products/srixon-zxi-hybrid.jpg",
    alt: "A Srixon ZXi hybrid, crown view, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "16 to 25 degrees",
  },
  {
    slug: "odyssey-dfx-one",
    brand: "Odyssey",
    model: "DFX One CH",
    category: "clubs",
    subcategory: "putters",
    price: 22900,
    statement: "A blade with a counter hang shaft. Strange to look at, easy to start on line.",
    image: "/images/products/odyssey-dfx-one.jpg",
    alt: "An Odyssey DFX One CH blade putter, seen from the toe, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "33, 34 and 35 inches",
  },
  {
    slug: "ping-g440-max-driver",
    brand: "Ping",
    model: "G440 Max Driver",
    category: "clubs",
    subcategory: "drivers",
    price: 52900,
    statement: "The forgiving one. Off centre still finds the short grass.",
    image: "/images/products/ping-g440-max-driver.jpg",
    alt: "A Ping G440 Max driver at address, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "9, 10.5 and 12 degrees",
  },
  {
    slug: "srixon-zxi-driver",
    brand: "Srixon",
    model: "ZXi Driver",
    category: "clubs",
    subcategory: "drivers",
    price: 44900,
    statement: "Quieter than most and the shape good players keep going back to.",
    image: "/images/products/srixon-zxi-driver.jpg",
    alt: "A Srixon ZXi driver, crown view, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "9.5 and 10.5 degrees",
  },
  {
    slug: "srixon-zxi-fairway",
    brand: "Srixon",
    model: "ZXi Fairway",
    category: "clubs",
    subcategory: "fairway woods",
    price: 26900,
    statement: "Shallow face, sits low. Easier off the deck than it looks.",
    image: "/images/products/srixon-zxi-fairway.jpg",
    alt: "A Srixon ZXi fairway wood, sole view, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "3, 5 and 7 wood",
  },
  {
    slug: "ping-g440-hybrid",
    brand: "Ping",
    model: "G440 Hybrid",
    category: "clubs",
    subcategory: "hybrids",
    price: 23900,
    statement: "Sits square at address, which is half the battle with a hybrid.",
    image: "/images/products/ping-g440-hybrid.jpg",
    alt: "A Ping G440 hybrid at address, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "17 to 30 degrees",
  },
  {
    slug: "ping-i530-irons",
    brand: "Ping",
    model: "i530 Irons",
    category: "clubs",
    subcategory: "irons",
    price: 119900,
    statement: "The distance iron for players who still want a thin top line.",
    image: "/images/products/ping-i530-irons.jpg",
    alt: "A Ping i530 seven iron, cavity side, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "7 clubs, 4 to PW",
  },
  {
    slug: "srixon-zx7-mk-ii-irons",
    brand: "Srixon",
    model: "ZX7 Mk II Irons",
    category: "clubs",
    subcategory: "irons",
    price: 109900,
    statement: "A forged tour blade with just enough help to be playable.",
    image: "/images/products/srixon-zx7-mk-ii-irons.jpg",
    alt: "A Srixon ZX7 Mk II seven iron, cavity side, on white",
    inStock: false,
    fittingRecommended: true,
    detail: "7 clubs, 4 to PW",
  },
  {
    slug: "ping-s159-wedge",
    brand: "Ping",
    model: "s159 Wedge",
    category: "clubs",
    subcategory: "wedges",
    price: 17900,
    statement: "Six grinds. More choice than anyone needs and exactly enough.",
    image: "/images/products/ping-s159-wedge.jpg",
    alt: "A Ping s159 wedge in chrome, seen from the toe, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "46 to 62 degrees",
  },
  {
    slug: "ping-scottsdale-tec",
    brand: "Ping",
    model: "Scottsdale TEC",
    category: "clubs",
    subcategory: "putters",
    price: 18900,
    statement: "A plain blade with an insert. Nothing to distract you at address.",
    image: "/images/products/ping-scottsdale-tec.jpg",
    alt: "A Ping Scottsdale TEC putter at address, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "33, 34 and 35 inches",
  },
  {
    slug: "ping-tri-fold-towel",
    brand: "Ping",
    model: "Tri-Fold Towel",
    category: "accessories",
    price: 2400,
    statement: "Three panels, one clean. The other two are for the grooves.",
    image: "/images/products/ping-tri-fold-towel.jpg",
    alt: "A folded Ping tri-fold golf towel, on white",
    inStock: true,
    detail: "Cotton, carabiner clip",
  },
  {
    slug: "ping-bow-tie-towel",
    brand: "Ping",
    model: "Bow Tie Towel",
    category: "accessories",
    price: 1900,
    statement: "Clips through the middle so it hangs where you can reach it.",
    image: "/images/products/ping-bow-tie-towel.jpg",
    alt: "A Ping bow tie golf towel laid flat, on white",
    inStock: true,
    detail: "Cotton, centre clip",
  },
  {
    slug: "ping-hoofer-14",
    brand: "Ping",
    model: "Hoofer 14",
    category: "bags",
    price: 24900,
    statement: "Fourteen dividers, so nothing tangles when you are in a hurry.",
    image: "/images/products/ping-hoofer-14.jpg",
    alt: "A Ping Hoofer 14 stand bag in deep red, legs out, on white",
    inStock: true,
    detail: "2.5 kg, 14 dividers",
  },
  {
    slug: "ping-hoofer-tour",
    brand: "Ping",
    model: "Hoofer Tour",
    category: "bags",
    price: 27900,
    statement: "Built heavier on purpose. It will outlast two of anything else.",
    image: "/images/products/ping-hoofer-tour.jpg",
    alt: "A Ping Hoofer Tour stand bag in white and black, on white",
    inStock: true,
    detail: "2.9 kg, tour build",
  },
  {
    slug: "ping-moonlite",
    brand: "Ping",
    model: "Moonlite",
    category: "bags",
    price: 16900,
    statement: "Two kilos is light. This is one. For nine holes after work.",
    image: "/images/products/ping-moonlite.jpg",
    alt: "A Ping Moonlite pencil bag in navy, rolled, on white",
    inStock: true,
    detail: "1.0 kg carry weight",
  },
  {
    slug: "ping-reserve-bag",
    brand: "Ping",
    model: "Reserve",
    category: "bags",
    price: 32900,
    statement: "The one people buy once and photograph on the first tee.",
    image: "/images/products/ping-reserve-bag.jpg",
    alt: "A Ping Reserve stand bag in white, legs out, on white",
    inStock: true,
    detail: "2.3 kg, leather trim",
  },
  {
    slug: "ping-pioneer",
    brand: "Ping",
    model: "Pioneer",
    category: "bags",
    price: 26900,
    statement: "A cart bag that has thought about where your hands go.",
    image: "/images/products/ping-pioneer.jpg",
    alt: "A Ping Pioneer cart bag in camouflage, on white",
    inStock: true,
    detail: "15 pockets, cart strap pass through",
  },
  {
    slug: "ping-traverse",
    brand: "Ping",
    model: "Traverse",
    category: "bags",
    price: 24900,
    statement: "Fits every trolley we have tried, which is not true of all of them.",
    image: "/images/products/ping-traverse.jpg",
    alt: "A Ping Traverse cart bag in heather grey, on white",
    inStock: true,
    detail: "14 way top, trolley base",
  },
  {
    slug: "ping-dlx",
    brand: "Ping",
    model: "DLX",
    category: "bags",
    price: 29900,
    statement: "Quiet colours, deep pockets. A cart bag for grown ups.",
    image: "/images/products/ping-dlx.jpg",
    alt: "A Ping DLX cart bag in navy, on white",
    inStock: false,
    detail: "14 way top, 12 pockets",
  },
  {
    slug: "titleist-pro-v1x",
    brand: "Titleist",
    model: "Pro V1x",
    category: "balls",
    price: 5200,
    statement: "Higher flight, firmer feel. The other half of the conversation.",
    image: "/images/products/titleist-pro-v1x.jpg",
    alt: "A box of a dozen Titleist Pro V1x golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "titleist-velocity",
    brand: "Titleist",
    model: "Velocity",
    category: "balls",
    price: 3000,
    statement: "Distance, and nothing pretending otherwise. Half the price too.",
    image: "/images/products/titleist-velocity.jpg",
    alt: "A box of a dozen Titleist Velocity golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "srixon-z-star",
    brand: "Srixon",
    model: "Z-STAR",
    category: "balls",
    price: 4500,
    statement: "The softer Z-Star. More spin into greens than the XV.",
    image: "/images/products/srixon-z-star.jpg",
    alt: "A box of a dozen Srixon Z-STAR golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "srixon-soft-feel",
    brand: "Srixon",
    model: "Soft Feel",
    category: "balls",
    price: 2400,
    statement: "Soft, cheap and honest about both. A good ball to learn on.",
    image: "/images/products/srixon-soft-feel.jpg",
    alt: "A box of a dozen Srixon Soft Feel golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "ping-captains-snapback",
    brand: "Ping",
    model: "Captain's Snapback",
    category: "headwear",
    price: 3200,
    statement: "Gold leaf on a navy crown. Louder than we usually go, and it works.",
    image: "/images/products/ping-captains-snapback.jpg",
    alt: "A navy Ping Captain's snapback cap with gold detailing, on white",
    inStock: true,
    detail: "One size, snapback",
  },
  {
    slug: "ping-wheel-boonie",
    brand: "Ping",
    model: "Wheel Boonie",
    category: "headwear",
    price: 3600,
    statement: "A full brim. Your neck will thank you in August.",
    image: "/images/products/ping-wheel-boonie.jpg",
    alt: "A white Ping wheel boonie hat, on white",
    inStock: true,
    detail: "S/M and L/XL",
  },
  {
    slug: "ping-get-a-grip-cap",
    brand: "Ping",
    model: "Get A Grip Cap",
    category: "headwear",
    price: 3000,
    statement: "Black on black. Nothing on it you have to explain.",
    image: "/images/products/ping-get-a-grip-cap.jpg",
    alt: "A black Ping cap with tonal detailing, on white",
    inStock: true,
    detail: "One size, adjustable",
  },
  {
    slug: "ping-phoenician-cap",
    brand: "Ping",
    model: "Phoenician Cap",
    category: "headwear",
    price: 3400,
    statement: "Rope brim, flat front. The one that looks better after a season.",
    image: "/images/products/ping-phoenician-cap.jpg",
    alt: "A tan Ping Phoenician rope cap, on white",
    inStock: true,
    detail: "One size, snapback",
  },
  {
    slug: "ping-single-canopy-umbrella",
    brand: "Ping",
    model: "Single Canopy Umbrella",
    category: "accessories",
    price: 4500,
    statement: "Single canopy, so it does not turn inside out in a links wind.",
    image: "/images/products/ping-single-canopy-umbrella.jpg",
    alt: "A black Ping single canopy golf umbrella, open, on white",
    inStock: true,
    detail: "62 inch canopy",
  },
  {
    slug: "ping-fur-driver-headcover",
    brand: "Ping",
    model: "Fur Driver Headcover",
    category: "accessories",
    price: 3500,
    statement: "It exists to stop your driver ringing against your irons.",
    image: "/images/products/ping-fur-driver-headcover.jpg",
    alt: "A black fur Ping driver headcover, on white",
    inStock: true,
    detail: "Fits up to 460cc",
  },
  {
    slug: "ping-captains-blade-cover",
    brand: "Ping",
    model: "Captain's Blade Cover",
    category: "accessories",
    price: 3200,
    statement: "Magnetic closure. You will put it back on, which is the point.",
    image: "/images/products/ping-captains-blade-cover.jpg",
    alt: "A navy Ping Captain's blade putter cover, on white",
    inStock: true,
    detail: "Blade putters, magnetic",
  },
  {
    slug: "ping-hoofer",
    brand: "Ping",
    model: "Hoofer",
    category: "bags",
    price: 22900,
    statement: "The original. Every carry bag since has been answering it.",
    image: "/images/products/ping-hoofer.jpg",
    alt: "A black Ping Hoofer stand bag, legs out, on white",
    inStock: true,
    detail: "2.3 kg, 5 way top",
  },
  {
    slug: "ping-moonlander",
    brand: "Ping",
    model: "Moonlander",
    category: "bags",
    price: 19900,
    statement: "Between the Moonlite and the Hoofer, for people who want both.",
    image: "/images/products/ping-moonlander.jpg",
    alt: "A patterned Ping Moonlander carry bag, on white",
    inStock: true,
    detail: "1.6 kg, 4 way top",
  },
  {
    slug: "srixon-z-star-diamond",
    brand: "Srixon",
    model: "Z-STAR Diamond",
    category: "balls",
    price: 4500,
    statement: "Built around the wedges. More spin in, less off the tee.",
    image: "/images/products/srixon-z-star-diamond.jpg",
    alt: "A box of a dozen Srixon Z-STAR Diamond golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "srixon-q-star-tour",
    brand: "Srixon",
    model: "Q-STAR Tour",
    category: "balls",
    price: 3400,
    statement: "Tour cover, slower compression. The sensible middle of the rack.",
    image: "/images/products/srixon-q-star-tour.jpg",
    alt: "A box of a dozen Srixon Q-STAR Tour golf balls in yellow",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "srixon-q-star-ultispeed",
    brand: "Srixon",
    model: "Q-STAR Ultispeed",
    category: "balls",
    price: 2800,
    statement: "Fast and cheap. It will not check, and it is not trying to.",
    image: "/images/products/srixon-q-star-ultispeed.jpg",
    alt: "A box of a dozen Srixon Q-STAR Ultispeed golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "srixon-soft-feel-brite",
    brand: "Srixon",
    model: "Soft Feel Brite",
    category: "balls",
    price: 2400,
    statement: "The Soft Feel in a colour you can find in the rough.",
    image: "/images/products/srixon-soft-feel-brite.jpg",
    alt: "A box of a dozen Srixon Soft Feel Brite golf balls in green",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "ping-sport-tech-glove",
    brand: "Ping",
    model: "Sport Tech Glove",
    category: "gloves",
    price: 1800,
    statement: "Part leather, part synthetic. It survives what cabretta will not.",
    image: "/images/products/ping-sport-tech-glove.jpg",
    alt: "A white Ping Sport Tech golf glove, on white",
    inStock: true,
    detail: "Sizes S to XL",
  },
  {
    slug: "ping-mr-ping-snapback",
    brand: "Ping",
    model: "Mr Ping Snapback",
    category: "headwear",
    price: 3200,
    statement: "The old mark, back where it belongs. Grey crown, gold figure.",
    image: "/images/products/ping-mr-ping-snapback.jpg",
    alt: "A grey Ping Mr Ping snapback cap, on white",
    inStock: true,
    detail: "One size, snapback",
  },
  {
    slug: "ping-finish-line-cap",
    brand: "Ping",
    model: "Finish Line Cap",
    category: "headwear",
    price: 2800,
    statement: "Unstructured and light. The one that folds into a pocket.",
    image: "/images/products/ping-finish-line-cap.jpg",
    alt: "A white Ping Finish Line cap, on white",
    inStock: true,
    detail: "One size, adjustable",
  },
  {
    slug: "ping-weekender-cap",
    brand: "Ping",
    model: "Weekender Cap",
    category: "headwear",
    price: 2800,
    statement: "Navy, soft front, nothing shouting. For the round after the round.",
    image: "/images/products/ping-weekender-cap.jpg",
    alt: "A navy Ping Weekender cap, on white",
    inStock: true,
    detail: "One size, adjustable",
  },
  {
    slug: "ping-icon-driver-cover",
    brand: "Ping",
    model: "Icon Driver Cover",
    category: "accessories",
    price: 3000,
    statement: "Plain, structured, and it holds its shape after a wet round.",
    image: "/images/products/ping-icon-driver-cover.jpg",
    alt: "A Ping Icon driver headcover, on white",
    inStock: true,
    detail: "Fits up to 460cc",
  },
  {
    slug: "ping-captains-driver-cover",
    brand: "Ping",
    model: "Captain's Driver Cover",
    category: "accessories",
    price: 3400,
    statement: "White, and it will not stay white. Some people like that.",
    image: "/images/products/ping-captains-driver-cover.jpg",
    alt: "A white Ping Captain's driver headcover, on white",
    inStock: true,
    detail: "Fits up to 460cc",
  },
  {
    slug: "ping-captains-mallet-cover",
    brand: "Ping",
    model: "Captain's Mallet Cover",
    category: "accessories",
    price: 3200,
    statement: "Mallets need a deeper cover. This is the one that fits.",
    image: "/images/products/ping-captains-mallet-cover.jpg",
    alt: "A white Ping Captain's mallet putter cover, on white",
    inStock: true,
    detail: "Mallet putters, magnetic",
  },
  {
    slug: "ping-fur-fairway-cover",
    brand: "Ping",
    model: "Fur Fairway Cover",
    category: "accessories",
    price: 3000,
    statement: "The fairway wood is the club that gets chipped. Cover it.",
    image: "/images/products/ping-fur-fairway-cover.jpg",
    alt: "A white fur Ping fairway wood headcover, on white",
    inStock: true,
    detail: "Fits 3, 5 and 7 wood",
  },
  {
    slug: "ping-icon-fairway-cover",
    brand: "Ping",
    model: "Icon Fairway Cover",
    category: "accessories",
    price: 2800,
    statement: "Numbered, so you stop pulling the wrong one out of the bag.",
    image: "/images/products/ping-icon-fairway-cover.jpg",
    alt: "A Ping Icon fairway wood headcover, on white",
    inStock: true,
    detail: "Numbered 3, 5 and 7",
  },
  {
    slug: "ping-stars-tri-fold-towel",
    brand: "Ping",
    model: "Stars Tri-Fold Towel",
    category: "accessories",
    price: 2400,
    statement: "Same towel, louder. It is easier to spot on a wet fairway.",
    image: "/images/products/ping-stars-tri-fold-towel.jpg",
    alt: "A red, white and navy Ping tri-fold golf towel, on white",
    inStock: true,
    detail: "Cotton, carabiner clip",
  },
  {
    slug: "callaway-tour-authentic-glove",
    brand: "Callaway",
    model: "Tour Authentic Glove",
    category: "gloves",
    price: 2200,
    statement: "Premium cabretta, nothing else. It wears out because it is good.",
    image: "/images/products/callaway-tour-authentic-glove.jpg",
    alt: "A white Callaway Tour Authentic golf glove, on white",
    inStock: true,
    detail: "Sizes S to XL",
  },
  {
    slug: "callaway-weather-spann-glove",
    brand: "Callaway",
    model: "Weather Spann Glove",
    category: "gloves",
    price: 1700,
    statement: "The one that still works when the grip is damp.",
    image: "/images/products/callaway-weather-spann-glove.jpg",
    alt: "A white Callaway Weather Spann golf glove, on white",
    inStock: true,
    detail: "Sizes S to XL",
  },
  {
    slug: "callaway-dawn-patrol-glove",
    brand: "Callaway",
    model: "Dawn Patrol Glove",
    category: "gloves",
    price: 1500,
    statement: "Full leather at the price people actually replace gloves at.",
    image: "/images/products/callaway-dawn-patrol-glove.jpg",
    alt: "A white Callaway Dawn Patrol golf glove, on white",
    inStock: true,
    detail: "Sizes S to XL",
  },
  {
    slug: "callaway-fusion-glove",
    brand: "Callaway",
    model: "Fusion Glove",
    category: "gloves",
    price: 1800,
    statement: "Leather on the palm, mesh over the knuckles. It breathes.",
    image: "/images/products/callaway-fusion-glove.jpg",
    alt: "A white Callaway Fusion golf glove, on white",
    inStock: true,
    detail: "Sizes S to XL",
  },
  {
    slug: "callaway-x-spann-glove",
    brand: "Callaway",
    model: "X-Spann Glove",
    category: "gloves",
    price: 2000,
    statement: "Cut tight. If you hate a glove that moves, this is yours.",
    image: "/images/products/callaway-x-spann-glove.jpg",
    alt: "A white Callaway X-Spann golf glove, on white",
    inStock: true,
    detail: "Sizes S to XL",
  },
  {
    slug: "callaway-rain-spann-gloves",
    brand: "Callaway",
    model: "Rain Spann Gloves",
    category: "gloves",
    price: 3000,
    statement: "A pair, because rain does not fall on one hand.",
    image: "/images/products/callaway-rain-spann-gloves.jpg",
    alt: "A black Callaway Rain Spann golf glove, on white",
    inStock: true,
    detail: "Pair, sizes S to XL",
  },
  {
    slug: "callaway-thermal-grip-gloves",
    brand: "Callaway",
    model: "Thermal Grip Gloves",
    category: "gloves",
    price: 2800,
    statement: "For the four months a year when you cannot feel the club.",
    image: "/images/products/callaway-thermal-grip-gloves.jpg",
    alt: "A Callaway Thermal Grip winter golf glove, on white",
    inStock: true,
    detail: "Pair, sizes S to XL",
  },
  {
    slug: "srixon-premium-cabretta-glove",
    brand: "Srixon",
    model: "Premium Cabretta Glove",
    category: "gloves",
    price: 2000,
    statement: "Thin leather, no panels, nothing between hand and grip.",
    image: "/images/products/srixon-premium-cabretta-glove.jpg",
    alt: "A white Srixon Premium Cabretta golf glove, on white",
    inStock: true,
    detail: "Sizes S to XL",
  },
  {
    slug: "srixon-all-weather-glove",
    brand: "Srixon",
    model: "All Weather Glove",
    category: "gloves",
    price: 1500,
    statement: "Synthetic where it wears. It outlasts leather and says less.",
    image: "/images/products/srixon-all-weather-glove.jpg",
    alt: "A white and grey Srixon All Weather golf glove, on white",
    inStock: true,
    detail: "Sizes S to XL",
  },
  {
    slug: "srixon-rain-gloves",
    brand: "Srixon",
    model: "Rain Gloves",
    category: "gloves",
    price: 2800,
    statement: "They grip better wet than dry. That is not a slogan, it is how they are made.",
    image: "/images/products/srixon-rain-gloves.jpg",
    alt: "A navy Srixon rain golf glove, on white",
    inStock: true,
    detail: "Pair, sizes S to XL",
  },
  {
    slug: "srixon-winter-cart-mitten",
    brand: "Srixon",
    model: "Winter Cart Mitten",
    category: "gloves",
    price: 2500,
    statement: "Not for swinging. For the four minutes between shots in February.",
    image: "/images/products/srixon-winter-cart-mitten.jpg",
    alt: "A pair of black Srixon winter cart mittens, on white",
    inStock: true,
    detail: "Pair, one size",
  },
  {
    slug: "srixon-junior-glove",
    brand: "Srixon",
    model: "All Weather Junior Glove",
    category: "gloves",
    price: 1200,
    statement: "A real glove in a small size, not a toy with a logo on it.",
    image: "/images/products/srixon-junior-glove.jpg",
    alt: "A white Srixon junior golf glove, on white",
    inStock: true,
    detail: "Junior sizes S to L",
  },
  {
    slug: "callaway-tour-authentic-performance-pro-hat",
    brand: "Callaway",
    model: "Tour Authentic Performance Pro Hat",
    category: "headwear",
    price: 2800,
    statement: "What the staff players wear, without the staff player on it.",
    image: "/images/products/callaway-tour-authentic-performance-pro-hat.jpg",
    alt: "A black Callaway Tour Authentic Performance Pro cap, on white",
    inStock: true,
    detail: "One size, adjustable",
  },
  {
    slug: "callaway-liquid-metal-hat",
    brand: "Callaway",
    model: "Liquid Metal Hat",
    category: "headwear",
    price: 3000,
    statement: "Navy, structured, and the badge catches light rather than shouting.",
    image: "/images/products/callaway-liquid-metal-hat.jpg",
    alt: "A navy Callaway Liquid Metal cap, on white",
    inStock: true,
    detail: "One size, adjustable",
  },
  {
    slug: "callaway-stretch-fit-fitted-hat",
    brand: "Callaway",
    model: "Stretch Fit Hat",
    category: "headwear",
    price: 2600,
    statement: "No strap at the back. If adjustable caps never sit right, try one.",
    image: "/images/products/callaway-stretch-fit-fitted-hat.jpg",
    alt: "A white Callaway Stretch Fit cap, on white",
    inStock: true,
    detail: "Fitted, S/M and L/XL",
  },
  {
    slug: "callaway-carlsbad-trucker-hat",
    brand: "Callaway",
    model: "Carlsbad Trucker Hat",
    category: "headwear",
    price: 2700,
    statement: "Mesh back, flat front. The one that comes off the course with you.",
    image: "/images/products/callaway-carlsbad-trucker-hat.jpg",
    alt: "A grey Callaway Carlsbad trucker cap, on white",
    inStock: true,
    detail: "One size, snapback",
  },
  {
    slug: "callaway-bucket-hat",
    brand: "Callaway",
    model: "Bucket Hat",
    category: "headwear",
    price: 3000,
    statement: "A brim all the way round. Your neck will thank you in July.",
    image: "/images/products/callaway-bucket-hat.jpg",
    alt: "A black Callaway bucket hat, on white",
    inStock: true,
    detail: "S/M and L/XL",
  },
  {
    slug: "callaway-liquid-metal-visor",
    brand: "Callaway",
    model: "Liquid Metal Visor",
    category: "headwear",
    price: 2500,
    statement: "Shade without the heat trapped on top of your head.",
    image: "/images/products/callaway-liquid-metal-visor.jpg",
    alt: "A white Callaway Liquid Metal visor, on white",
    inStock: true,
    detail: "One size, adjustable",
  },
  {
    slug: "callaway-heritage-twill-hat",
    brand: "Callaway",
    model: "Heritage Twill Hat",
    category: "headwear",
    price: 2400,
    statement: "Cotton twill, soft front, and yes, that is an American flag.",
    image: "/images/products/callaway-heritage-twill-hat.jpg",
    alt: "A white Callaway Heritage Twill cap with a flag patch, on white",
    inStock: true,
    detail: "One size, adjustable",
  },
  {
    slug: "srixon-tour-tech-hat",
    brand: "Srixon",
    model: "Tour Tech Hat",
    category: "headwear",
    price: 2600,
    statement: "Structured front, technical fabric. It dries on the walk in.",
    image: "/images/products/srixon-tour-tech-hat.jpg",
    alt: "A navy Srixon Tour Tech cap, on white",
    inStock: true,
    detail: "One size, adjustable",
  },
  {
    slug: "srixon-genuine-tour-hat",
    brand: "Srixon",
    model: "Genuine Tour Hat",
    category: "headwear",
    price: 2800,
    statement: "The tour issue cap, exactly as it leaves the truck.",
    image: "/images/products/srixon-genuine-tour-hat.jpg",
    alt: "A black Srixon Genuine Tour cap, on white",
    inStock: true,
    detail: "One size, adjustable",
  },
  {
    slug: "srixon-tour-bucket-hat",
    brand: "Srixon",
    model: "Tour Bucket Hat",
    category: "headwear",
    price: 3000,
    statement: "White, wide, and it packs flat in the bag pocket.",
    image: "/images/products/srixon-tour-bucket-hat.jpg",
    alt: "A white Srixon Tour bucket hat, on white",
    inStock: true,
    detail: "S/M and L/XL",
  },
  {
    slug: "cleveland-structured-cap",
    brand: "Cleveland",
    model: "Structured Cap",
    category: "headwear",
    price: 2400,
    statement: "White crown, black script. It has looked like this for years.",
    image: "/images/products/cleveland-structured-cap.jpg",
    alt: "A white Cleveland Golf structured cap, on white",
    inStock: true,
    detail: "One size, adjustable",
  },
  {
    slug: "cleveland-bucket-hat",
    brand: "Cleveland",
    model: "Bucket Hat",
    category: "headwear",
    price: 2800,
    statement: "Charcoal, so it does not look new for one round and grubby after.",
    image: "/images/products/cleveland-bucket-hat.jpg",
    alt: "A charcoal Cleveland Golf bucket hat, on white",
    inStock: true,
    detail: "S/M and L/XL",
  },
  {
    slug: "cleveland-leather-patch-hat",
    brand: "Cleveland",
    model: "Leather Patch Hat",
    category: "headwear",
    price: 2700,
    statement: "One patch, no embroidery. It ages the way leather does.",
    image: "/images/products/cleveland-leather-patch-hat.jpg",
    alt: "A black Cleveland Golf cap with a leather patch, on white",
    inStock: true,
    detail: "One size, adjustable",
  },
  {
    slug: "cleveland-retro-snapback",
    brand: "Cleveland",
    model: "Retro Snapback",
    category: "headwear",
    price: 2600,
    statement: "The old script, flat brim, snapback. Nothing modern about it.",
    image: "/images/products/cleveland-retro-snapback.jpg",
    alt: "A black Cleveland Golf retro snapback cap, on white",
    inStock: true,
    detail: "One size, snapback",
  },
  {
    slug: "callaway-premium-driver-headcover",
    brand: "Callaway",
    model: "Premium Driver Headcover",
    category: "accessories",
    price: 3000,
    statement: "Leather look, lined, and it goes back on in the rain.",
    image: "/images/products/callaway-premium-driver-headcover.jpg",
    alt: "A white Callaway Premium driver headcover, on white",
    inStock: true,
    detail: "Fits up to 460cc",
  },
  {
    slug: "callaway-premium-fairway-headcover",
    brand: "Callaway",
    model: "Premium Fairway Headcover",
    category: "accessories",
    price: 2800,
    statement: "Marked F, so you stop pulling the wrong one on a tight tee.",
    image: "/images/products/callaway-premium-fairway-headcover.jpg",
    alt: "A black Callaway Premium fairway wood headcover, on white",
    inStock: true,
    detail: "Fits 3, 5 and 7 wood",
  },
  {
    slug: "callaway-premium-hybrid-headcover",
    brand: "Callaway",
    model: "Premium Hybrid Headcover",
    category: "accessories",
    price: 2600,
    statement: "Hybrids are the clubs that rattle. Cover them.",
    image: "/images/products/callaway-premium-hybrid-headcover.jpg",
    alt: "A navy Callaway Premium hybrid headcover, on white",
    inStock: true,
    detail: "Fits most hybrid heads",
  },
  {
    slug: "callaway-magnetic-iron-headcovers",
    brand: "Callaway",
    model: "Magnetic Iron Headcovers",
    category: "accessories",
    price: 4500,
    statement: "Ten covers. Your irons stop chewing each other in the bag.",
    image: "/images/products/callaway-magnetic-iron-headcovers.jpg",
    alt: "A black Callaway magnetic iron headcover on an iron, on white",
    inStock: true,
    detail: "Set of 10, magnetic",
  },
  {
    slug: "callaway-vintage-driver-headcover",
    brand: "Callaway",
    model: "Vintage Driver Headcover",
    category: "accessories",
    price: 3200,
    statement: "Striped, barrel shaped, and older looking than anything in your bag.",
    image: "/images/products/callaway-vintage-driver-headcover.jpg",
    alt: "A striped Callaway Vintage barrel driver headcover, on white",
    inStock: true,
    detail: "Fits up to 460cc",
  },
  {
    slug: "callaway-tour-fold-towel",
    brand: "Callaway",
    model: "Tour Fold Towel",
    category: "accessories",
    price: 2200,
    statement: "Waffle weave on one face, smooth on the other. Both have a job.",
    image: "/images/products/callaway-tour-fold-towel.jpg",
    alt: "A black and grey Callaway Tour Fold golf towel, on white",
    inStock: true,
    detail: "Two faces, clip",
  },
  {
    slug: "callaway-trifold-towel",
    brand: "Callaway",
    model: "Trifold Towel",
    category: "accessories",
    price: 2000,
    statement: "Three panels. One wet, two dry, and that is the whole idea.",
    image: "/images/products/callaway-trifold-towel.jpg",
    alt: "A white Callaway trifold golf towel, on white",
    inStock: true,
    detail: "Cotton, carabiner clip",
  },
  {
    slug: "callaway-players-towel",
    brand: "Callaway",
    model: "Outperform Players Towel",
    category: "accessories",
    price: 2500,
    statement: "Bigger than it looks and it holds more water than it should.",
    image: "/images/products/callaway-players-towel.jpg",
    alt: "A navy Callaway Outperform players towel, on white",
    inStock: true,
    detail: "Microfibre, clip",
  },
  {
    slug: "odyssey-microfibre-towel",
    brand: "Odyssey",
    model: "Microfibre Towel",
    category: "accessories",
    price: 2200,
    statement: "For the putter face and the ball, not the mud.",
    image: "/images/products/odyssey-microfibre-towel.jpg",
    alt: "A white Odyssey microfibre golf towel, on white",
    inStock: true,
    detail: "Microfibre, clip",
  },
  {
    slug: "odyssey-tempest-blade-headcover",
    brand: "Odyssey",
    model: "Tempest Blade Headcover",
    category: "accessories",
    price: 3000,
    statement: "A blade cover that actually fits a blade. Most do not.",
    image: "/images/products/odyssey-tempest-blade-headcover.jpg",
    alt: "A chequered Odyssey Tempest blade putter headcover, on white",
    inStock: true,
    detail: "Blade putters, magnetic",
  },
  {
    slug: "odyssey-tempest-mallet-headcover",
    brand: "Odyssey",
    model: "Tempest Mallet Headcover",
    category: "accessories",
    price: 3200,
    statement: "Cut deep for a mallet, so it stays on to the third green.",
    image: "/images/products/odyssey-tempest-mallet-headcover.jpg",
    alt: "A chequered Odyssey Tempest mallet putter headcover, on white",
    inStock: true,
    detail: "Mallet putters, magnetic",
  },
  {
    slug: "callaway-fairway-14-stand-bag",
    brand: "Callaway",
    model: "Fairway 14 Stand Bag",
    category: "bags",
    price: 26500,
    statement: "Fourteen slots on a carry bag, which is rarer than it should be.",
    image: "/images/products/callaway-fairway-14-stand-bag.jpg",
    alt: "A dark red Callaway Fairway 14 stand bag, legs out, on white",
    inStock: true,
    detail: "2.5 kg, 14 way top",
  },
  {
    slug: "callaway-fairway-c-stand-bag",
    brand: "Callaway",
    model: "Fairway C Stand Bag",
    category: "bags",
    price: 21500,
    statement: "Double strap, four way top, and light enough to mean it.",
    image: "/images/products/callaway-fairway-c-stand-bag.jpg",
    alt: "A blue and grey Callaway Fairway C stand bag, legs out, on white",
    inStock: true,
    detail: "2.0 kg, 4 way top",
  },
  {
    slug: "callaway-hyperlite-zero-stand-bag",
    brand: "Callaway",
    model: "Hyperlite Zero Stand Bag",
    category: "bags",
    price: 18500,
    statement: "The lightest thing in the shop with legs on it.",
    image: "/images/products/callaway-hyperlite-zero-stand-bag.jpg",
    alt: "A dark green Callaway Hyperlite Zero stand bag, on white",
    inStock: true,
    detail: "1.4 kg, 4 way top",
  },
  {
    slug: "callaway-org-14-cart-bag",
    brand: "Callaway",
    model: "ORG 14 Cart Bag",
    category: "bags",
    price: 25000,
    statement: "Full length dividers, so the grips do not fight on the way round.",
    image: "/images/products/callaway-org-14-cart-bag.jpg",
    alt: "A black Callaway ORG 14 cart bag, on white",
    inStock: true,
    detail: "14 way, full length",
  },
  {
    slug: "callaway-chase-stand-bag",
    brand: "Callaway",
    model: "Chase Stand Bag",
    category: "bags",
    price: 19500,
    statement: "Plain black, four pockets, and nothing you will not use.",
    image: "/images/products/callaway-chase-stand-bag.jpg",
    alt: "A black Callaway Chase stand bag, legs out, on white",
    inStock: true,
    detail: "2.2 kg, 4 way top",
  },
  {
    slug: "callaway-par-3-stand-bag",
    brand: "Callaway",
    model: "Par 3 Stand Bag",
    category: "bags",
    price: 12000,
    statement: "Seven clubs, nine holes, nothing more asked of it.",
    image: "/images/products/callaway-par-3-stand-bag.jpg",
    alt: "A black Callaway Par 3 stand bag, legs out, on white",
    inStock: true,
    detail: "1.3 kg, 4 way top",
  },
  {
    slug: "odyssey-shadow-stand-bag",
    brand: "Odyssey",
    model: "Shadow Stand Bag",
    category: "bags",
    price: 24000,
    statement: "Built by Ogio, badged Odyssey, and the harness is the reason to buy it.",
    image: "/images/products/odyssey-shadow-stand-bag.jpg",
    alt: "A navy and white Odyssey Shadow stand bag, legs out, on white",
    inStock: true,
    detail: "2.4 kg, 4 way top",
  },
  {
    slug: "callaway-chrome-tour",
    brand: "Callaway",
    model: "Chrome Tour",
    category: "balls",
    price: 5200,
    statement: "The one that made people stop assuming the tour ball came from one place.",
    image: "/images/products/callaway-chrome-tour.jpg",
    alt: "A box of a dozen Callaway Chrome Tour golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "callaway-chrome-tour-x",
    brand: "Callaway",
    model: "Chrome Tour X",
    category: "balls",
    price: 5200,
    statement: "Firmer, lower spinning, and it needs speed to make sense.",
    image: "/images/products/callaway-chrome-tour-x.jpg",
    alt: "A box of a dozen Callaway Chrome Tour X golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "callaway-chrome-soft-triple-track",
    brand: "Callaway",
    model: "Chrome Soft Triple Track",
    category: "balls",
    price: 4500,
    statement: "The same ball with three lines on it. Some people putt better for it.",
    image: "/images/products/callaway-chrome-soft-triple-track.jpg",
    alt: "A box of a dozen Callaway Chrome Soft Triple Track golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "callaway-supersoft",
    brand: "Callaway",
    model: "Supersoft",
    category: "balls",
    price: 2500,
    statement: "The best selling ball in Britain, and not by accident.",
    image: "/images/products/callaway-supersoft.jpg",
    alt: "A box of a dozen Callaway Supersoft golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "callaway-supersoft-max",
    brand: "Callaway",
    model: "Supersoft MAX",
    category: "balls",
    price: 2500,
    statement: "Oversized, and legal. For slower speeds that need help getting up.",
    image: "/images/products/callaway-supersoft-max.jpg",
    alt: "A box of a dozen Callaway Supersoft MAX golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "callaway-erc-soft",
    brand: "Callaway",
    model: "ERC Soft",
    category: "balls",
    price: 3500,
    statement: "Soft feel with more carry than soft balls usually manage.",
    image: "/images/products/callaway-erc-soft.jpg",
    alt: "A box of a dozen Callaway ERC Soft golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "callaway-warbird",
    brand: "Callaway",
    model: "Warbird Distance+",
    category: "balls",
    price: 2000,
    statement: "Long, cheap, and it will not check. It does not pretend otherwise.",
    image: "/images/products/callaway-warbird.jpg",
    alt: "A box of a dozen Callaway Warbird Distance+ golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "callaway-elyte-driver",
    brand: "Callaway",
    model: "Elyte Driver",
    category: "clubs",
    subcategory: "drivers",
    price: 54900,
    statement: "The standard head. Neutral, forgiving, and the one most people leave with.",
    image: "/images/products/callaway-elyte-driver.jpg",
    alt: "A Callaway Elyte driver head at address, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "9, 10.5 and 12 degrees",
  },
  {
    slug: "callaway-elyte-triple-diamond-driver",
    brand: "Callaway",
    model: "Elyte Triple Diamond Driver",
    category: "clubs",
    subcategory: "drivers",
    price: 54900,
    statement: "Smaller, lower spinning, less forgiving. It is not for most people.",
    image: "/images/products/callaway-elyte-triple-diamond-driver.jpg",
    alt: "A Callaway Elyte Triple Diamond driver head at address, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "8, 9 and 10.5 degrees",
  },
  {
    slug: "callaway-elyte-fairway",
    brand: "Callaway",
    model: "Elyte Fairway Woods",
    category: "clubs",
    subcategory: "fairway woods",
    price: 29900,
    statement: "Shallow enough to use off the deck, which is the only reason to carry one.",
    image: "/images/products/callaway-elyte-fairway.jpg",
    alt: "A Callaway Elyte fairway wood head at address, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "3, 5 and 7 wood",
  },
  {
    slug: "callaway-elyte-hybrid",
    brand: "Callaway",
    model: "Elyte Hybrids",
    category: "clubs",
    subcategory: "hybrids",
    price: 24900,
    statement: "Four lofts. Pick by the gap in your bag, never by the number on the sole.",
    image: "/images/products/callaway-elyte-hybrid.jpg",
    alt: "A Callaway Elyte hybrid head at address, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "18 to 27 degrees",
  },
  {
    slug: "callaway-apex-ai200-irons",
    brand: "Callaway",
    model: "Apex Ai200 Irons",
    category: "clubs",
    subcategory: "irons",
    price: 129900,
    statement: "A players distance iron that does not look like one at address.",
    image: "/images/products/callaway-apex-ai200-irons.jpg",
    alt: "A Callaway Apex Ai200 seven iron at address, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "7 clubs, 4 to PW",
  },
  {
    slug: "callaway-apex-cb-irons",
    brand: "Callaway",
    model: "Apex CB Irons",
    category: "clubs",
    subcategory: "irons",
    price: 149900,
    statement: "Forged cavity back, traditional lofts, no help you did not ask for.",
    image: "/images/products/callaway-apex-cb-irons.jpg",
    alt: "A Callaway Apex CB seven iron at address, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "7 clubs, 4 to PW",
  },
  {
    slug: "callaway-opus-wedge",
    brand: "Callaway",
    model: "Opus Wedge",
    category: "clubs",
    subcategory: "wedges",
    price: 16900,
    statement: "Four grinds. One of them matches your turf and it is worth finding out which.",
    image: "/images/products/callaway-opus-wedge.jpg",
    alt: "A Callaway Opus wedge at address, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "48 to 60 degrees",
  },
  {
    slug: "callaway-jaws-raw-wedge",
    brand: "Callaway",
    model: "Jaws Raw Wedge",
    category: "clubs",
    subcategory: "wedges",
    price: 14900,
    statement: "Raw face. It rusts, and the rust is the point.",
    image: "/images/products/callaway-jaws-raw-wedge.jpg",
    alt: "A Callaway Jaws Raw wedge at address, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "50 to 60 degrees",
  },
  {
    slug: "ping-i230-irons",
    brand: "Ping",
    model: "i230 Irons",
    category: "clubs",
    subcategory: "irons",
    price: 109900,
    statement: "A cavity that looks like a blade the moment you set it down.",
    image: "/images/products/ping-i230-irons.jpg",
    alt: "A Ping i230 seven iron, cavity side, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "7 clubs, 4 to PW",
  },
  {
    slug: "mizuno-jpx925-forged",
    brand: "Mizuno",
    model: "JPX925 Forged",
    category: "clubs",
    subcategory: "irons",
    price: 119900,
    statement: "Grain flow forged. You feel the strike before you see it.",
    image: "/images/products/mizuno-jpx925-forged.jpg",
    alt: "A Mizuno JPX925 Forged seven iron, cavity side, on white",
    inStock: true,
    fittingRecommended: true,
    detail: "7 clubs, 4 to PW",
  },
  {
    slug: "callaway-chrome-soft",
    brand: "Callaway",
    model: "Chrome Soft",
    category: "balls",
    price: 4800,
    statement: "Softer off the face than the Pro V1. Some players never go back.",
    image: "/images/products/callaway-chrome-soft.jpg",
    alt: "A box of a dozen Callaway Chrome Soft golf balls",
    inStock: true,
    detail: "Dozen",
  },
  {
    slug: "ping-tour-glove",
    brand: "Ping",
    model: "Tour Glove",
    category: "gloves",
    price: 2400,
    statement: "Cabretta leather. Wears out because it fits, not because it is cheap.",
    image: "/images/products/ping-tour-glove.jpg",
    alt: "A white Ping Tour cabretta leather golf glove, on white",
    inStock: true,
    detail: "Sizes S to XL",
  },
  {
    slug: "ping-tour-vented-delta",
    brand: "Ping",
    model: "Tour Vented Delta",
    category: "headwear",
    price: 3200,
    statement: "Laser cut vents on the crown. The one the staff wear in July.",
    image: "/images/products/ping-tour-vented-delta.jpg",
    alt: "A black Ping Tour Vented Delta cap, on white",
    inStock: true,
    detail: "One size, snapback",
  },
  {
    slug: "srixon-z-star-xv",
    brand: "Srixon",
    model: "Z-STAR XV",
    category: "balls",
    price: 4500,
    statement: "The firmer of the two Z-Stars. Take it if you spin it too much.",
    image: "/images/products/srixon-z-star-xv.jpg",
    alt: "A box of a dozen Srixon Z-STAR XV golf balls",
    inStock: true,
    detail: "Dozen",
  },
];

/** the four on the homepage grid */
export const featuredProducts = products.filter((product) => product.featured);

const categoryNames: Record<Category, string> = {
  clubs: "Clubs",
  balls: "Balls",
  bags: "Bags",
  gloves: "Gloves",
  headwear: "Headwear",
  accessories: "Accessories",
};

/**
 * Derived from the rack rather than written out, so the shop can never
 * advertise a shelf with nothing on it.
 */
export const shopCategories = (Object.keys(categoryNames) as Category[])
  .map((slug) => ({
    slug,
    name: categoryNames[slug],
    count: products.filter((product) => product.category === slug).length,
  }))
  .filter((category) => category.count > 0);

export const shopBrands = [...new Set(products.map((product) => product.brand))]
  .sort((a, b) => a.localeCompare(b))
  .map((name) => ({
    name,
    count: products.filter((product) => product.brand === name).length,
  }));

export function isCategory(value: string): value is Category {
  return value in categoryNames;
}

export function categoryName(slug: Category) {
  return categoryNames[slug];
}

export function findProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function formatPrice(pence: number) {
  return new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
    minimumFractionDigits: pence % 100 === 0 ? 0 : 2,
  }).format(pence / 100);
}
